### ISSUE TITLE
Test domain adaptation?

### ISSUE THREAD

**Issue by hbredin** [displace2023/DISPLACE_Baselines#3]
Thanks for organizing this challenge!

Assuming the two assumptions below are correct:

- [x] the test set contains several audio files
- [x] the evaluation metric (diarization error rate) is computed on each file separately

Can you please clarify whether the diarization systems 
- [x] must process each test file independently of the other test files
- [ ] can make use of other test files when processing a particular test file (e.g. for [unsupervised test domain adaptation](https://arxiv.org/abs/2106.04764))

**Comment by shreyas2206** [comment]
- The evaluation metric is computed on each file separately and averaged across all the test files.
 - You CAN NOT make use of other test files while processing a particular test file, but you can make use of the development data.

**Comment by hbredin** [comment]
Thanks!
